baseURL: https://kiranmarturu.com
languageCode: en-us
title: Kiran Marturu

theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "Hello, this is Kiran."
    subtitle: "I eat to code and code to eat ;-)"
    buttons:
      - name: Dev Note's
        url: https://kiramrtr.github.io/dev-notes
  socialIcons:
    - name: "GitHub"
      url: "https://github.com/kiramrtr"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/kiran-marturu/"
